### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by tsherif** [xeolabs/scenejs#456] opened 2016-03-15 22:48 UTC
http://scenejs.org/examples/index.html#geometry_morphTargets
http://scenejs.org/examples/index.html#geometry_morphTargets_typedArrays
http://scenejs.org/examples/index.html#optimization_vertexSharing
http://scenejs.org/examples/index.html#geometry_editing_indices
http://scenejs.org/examples/index.html#texture_procedural_color_grid
http://scenejs.org/examples/index.html#skyboxes_reflect (Doesn't exist)
http://scenejs.org/examples/index.html#postprocessing_depthOfField_autofocus_grid
http://scenejs.org/examples/index.html#picking_rayPicking
http://scenejs.org/examples/index.html#picking_rayPicking_morphTargets
http://scenejs.org/examples/index.html#importing_md2_lion
http://scenejs.org/examples/index.html#importing_obj_hand (Doesn't exist)
http://scenejs.org/examples/index.html#optimization_vertexSharing

**Comment by xeolabs** [comment] 2016-03-15 23:17
Wow I forgot to test those ones after adding the multiple UV layers. Aside from the missing examples,  these breakages are caused by incomplete implementation of multiple UV layers. They will be fixed by the merge I'm about to do tomorrow morning, which fixes these exact breakages. I'm also going to set up a QA branch for SceneJS to keep master stable.

**Comment by xeolabs** [comment] 2016-03-16 08:06
Confirmed that all these (except for the missing examples) are fixed by the update I'm about to merge. I'm going to create a "dev" branch to help keep master stable, plus a contribution guidelines doc.

**Comment by xeolabs** [comment] 2016-03-16 13:56
Fixed by https://github.com/xeolabs/scenejs/pull/467 except for:

Removed link (1): http://scenejs.org/examples/index.html#geometry_editing_indices 
Removed link (2): http://scenejs.org/examples/index.html#texture_procedural_color_grid
Removed link (3): http://scenejs.org/examples/index.html#skyboxes_reflect (Doesn't exist)
Removed link (2):  http://scenejs.org/examples/index.html#postprocessing_depthOfField_autofocus_grid
Removed link (3): http://scenejs.org/examples/index.html#importing_obj_hand 

(1) Feature not supported yet
(2) Broken by unrelated issue:
(3) Example page didn't exist

**Closed by xeolabs** 2016-03-16 13:56 UTC
